main: pw.neryss.plugin.Main
name: Test
version: 0.1.0
author: neryss
api-version: 1.17

commands:
   hello:
      usage: /<command>
      description: test
   launch:
      usage: /<command> [velocity]
      description: goes vroom
      aliases: lch
   doctor:
      usage: /<command>
   boots:
      usage: /<command>
   starstaff:
      usage: /<command>
   skull:
      usage: /<command> [name]
   changeteam:
      usage: /<command>