main: pw.neryss.plugin.Main
name: Test
version: 0.0.1
author: neryss

commands:
   hello:
      usage: /<command>
      description: test
   launch:
      usage: /<command> [velocity]
      description: goes vroom
      aliases: lch
   doctor:
      usage: /<command>
   boots:
      usage: /<command>